version: '3.1'

volumes:
  mail:
  
services:

  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - mail:/home/mailhog
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /home/mailhog
      